# coffee mill input file for dcd-mode, make-movie job.
# use this way
#    $ mill dcd make-movie dcd2movie.inp

# name of output file
output   = "fromdcd.movie"

# name of input file
dcdfile = "trajectory.dcd"

# pdb file of reference. using this information, write atom and residue information.
pdbfile = "structure.pdb"

# if true,  output pymol readable format movie file.
# if false, output cafemol compatible format movie file.
pymol = true
