# coffee mill input file for dcd join.
# use this way
#    $ mill dcd --join dcdjoin.inp

[information]

# key: output 
#      filename of output
output   = "joined.dcd"

# key: dcdfiles
#      files to join(join these files in this order)
dcdfiles = ["dcdfile1.dcd", "dcdfile2.dcd",
            "dcdfile3.dcd"]

# key: redundancy
#      if true, join dcdfiles as it is.
#      if false, remove initial snapshot from input dcdfiles except first file.
redundancy = false

